//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PompeiiSquare.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PompeiiSquare.Server.AppKeys", typeof(AppKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1600624730193996.
        /// </summary>
        internal static string FacebookAppId {
            get {
                return ResourceManager.GetString("FacebookAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04fb38d0a6d4ab9efa336d4ab711c039.
        /// </summary>
        internal static string FacebookAppSecret {
            get {
                return ResourceManager.GetString("FacebookAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41554252794-u8kddu89mbnsvlaa4s2hja0dbof57720.apps.googleusercontent.com.
        /// </summary>
        internal static string GoogleClientId {
            get {
                return ResourceManager.GetString("GoogleClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-apREqxtVNVoRkmd1X5YEhD.
        /// </summary>
        internal static string GoogleClientSecret {
            get {
                return ResourceManager.GetString("GoogleClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000040157824.
        /// </summary>
        internal static string MicrosoftClientId {
            get {
                return ResourceManager.GetString("MicrosoftClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuVghI06AQoxZwKog4Sjng7GEZv2xb4.
        /// </summary>
        internal static string MicrosoftClientSecret {
            get {
                return ResourceManager.GetString("MicrosoftClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lysBeJqQj2Yh7ZD4WCfyfk3LG.
        /// </summary>
        internal static string TwitterConsumerKey {
            get {
                return ResourceManager.GetString("TwitterConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nZ46aWAgVHxWyFkQ5TXGKN6dHVdVNi5B9LqDIkzAPV6ZLoXGtx.
        /// </summary>
        internal static string TwitterConsumerSecret {
            get {
                return ResourceManager.GetString("TwitterConsumerSecret", resourceCulture);
            }
        }
    }
}
